backend:
  name: git-gateway
  repo: Marcicano/Sabaai-Webiste
# publish_mode: editorial_workflow
media_folder: static/images/uploads
public_folder: /images/uploads
collections:
  - name: sabaai # Used in routes, e.g., /admin/collections/blog
    label: "Formacao" # Used in the UI
    folder: "../../../../content/cursos/formacao.md" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "title", name: "title", widget: "string"}
      - {label: "date", name: "date", widget: "date"}
      - {label: "description", name: "description", widget: "string"}
      
   