title = "SABAAI"
baseURL = "https://www.sabaai.com.br"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-128248261-1"
# disqusShortname = "tomanistor"
staticDir = "/static"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Sabaai, a Tailândia nas suas mãos"
    author = "Sabaai Thai"
    description = "Thai Massage nas suas mãos através dos melhores cursos do mercado. Direto da Tailândia ao Brasil. Venha fazer uma viagem à Tailândia conosco!"
    logoBig = "/images/logo.png"
    logoSmall = "/images/logo-small.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/logo.png"
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "Cursos"
    url  = "/#gallery"
    weight = 1

[[menu.main]]
    name = "Nós"
    url  = "/#nos"
    weight = 2
[[menu.main]]
    name = "Viagem"
    url  = "/#viagem"
    weight = 3
[[menu.main]]
    name = "Contato"
    url  = "/#contact"
    weight = 4