title = "SABAAI"
baseURL = "https://sabaai.com.br"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
# disqusShortname = "tomanistor"
staticDir = "/static"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Thailand + You"
    author = "Sabaai Thai"
    description = "Long and tedious description about Sabaai"
    logoBig = "/images/logo.png"
    logoSmall = "/images/logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey-logo.png"
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "Sobre"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Cursos"
    url  = "/#cursos"
    weight = 2
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
