backend:
  name: git-gateway
  repo: Marcicano/one-click-hugo-cms
  branch: master # Branch to update (optional; defaults to master)
  media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
 

  collections:
  - name: "sabaai" # Used in routes, e.g., /admin/collections/blog
    label: "Sabaai" # Used in the UI
    folder: "../../content/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "layout", name: "layout", widget: "string"}
      - {label: "id", name: "id", widget: "string"}
      - {label: "content", name: "content", widget: "string"}